// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM4q8d8h0qn0xT2xVFnTxtw1PEBQjowxo',
    appId: '1:133957221117:web:fd6a9c46799fab0f0cdc94',
    messagingSenderId: '133957221117',
    projectId: 'whatsapp-1041e',
    authDomain: 'whatsapp-1041e.firebaseapp.com',
    storageBucket: 'whatsapp-1041e.appspot.com',
    measurementId: 'G-DDC4791KRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNsR-OYU7CKHTktUcKtlUpnlrX9YTXNBs',
    appId: '1:133957221117:android:449c53789fad13810cdc94',
    messagingSenderId: '133957221117',
    projectId: 'whatsapp-1041e',
    storageBucket: 'whatsapp-1041e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6it4qhmk3W2h9sDvaZUR3ifS6rl0VB8',
    appId: '1:133957221117:ios:8c928fac232933420cdc94',
    messagingSenderId: '133957221117',
    projectId: 'whatsapp-1041e',
    storageBucket: 'whatsapp-1041e.appspot.com',
    iosClientId: '133957221117-crtedbdl6vleg36onvo6n7ld186gi5mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6it4qhmk3W2h9sDvaZUR3ifS6rl0VB8',
    appId: '1:133957221117:ios:8c928fac232933420cdc94',
    messagingSenderId: '133957221117',
    projectId: 'whatsapp-1041e',
    storageBucket: 'whatsapp-1041e.appspot.com',
    iosClientId: '133957221117-crtedbdl6vleg36onvo6n7ld186gi5mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
